version: '3.8'
services:
  postgres:
    image: postgres:18.1
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: yeobaek
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
volumes:
  postgres_data: