spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/yeobaek
    username: ${LOCAL_DB_ID:nova}
    password: ${LOCAL_DB_PW:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Flyway가 DDL 담당 -> validate나 none으로 둬야 함
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.nova.yeobaek: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.oauth2.client: DEBUG

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: ${JWT_ACCESS_EXPIRATION:1800000}   # 30분
      refresh: ${JWT_REFRESH_EXPIRATION:604800000} # 7일
