spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PROD_RDS_ENDPOINT}:5432/yeobaek
    username: ${PROD_RDS_USERNAME}
    password: ${PROD_RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ${PROD_REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
logging:
  level:
    com.nova.yeobaek: info
    org.hibernate.SQL: info
jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: ${JWT_ACCESS_EXPIRATION:1800000}   # 30분
      refresh: ${JWT_REFRESH_EXPIRATION:604800000} # 7일