-- 테이블 생성
create table brands (
                        created_at timestamp(6) not null,
                        id bigint generated by default as identity,
                        updated_at timestamp(6) not null,
                        name varchar(255) not null,
                        primary key (id),
                        constraint uk_brand_name unique (name)
);
create table calendars (
                           date date not null,
                           created_at timestamp(6) not null,
                           id bigint generated by default as identity,
                           ootd_id bigint,
                           updated_at timestamp(6) not null,
                           user_id bigint,
                           custom_image_url TEXT,
                           ootd_image_url TEXT not null,
                           thumbnail VARCHAR DEFAULT 'OOTD' not null check (thumbnail in ('OOTD','CUSTOM')),
                           primary key (id),
                           constraint uk_user_date unique (user_id, date)
);
create table categories (
                            level integer not null,
                            created_at timestamp(6) not null,
                            id bigint generated by default as identity,
                            parent_id bigint,
                            updated_at timestamp(6) not null,
                            name varchar(255) not null,
                            primary key (id)
);
create table closet_items (
                              closet_id bigint,
                              created_at timestamp(6) not null,
                              id bigint generated by default as identity,
                              item_id bigint,
                              updated_at timestamp(6) not null,
                              primary key (id),
                              constraint uk_closet_item unique (closet_id, item_id)
);
create table closets (
                         favorite boolean not null,
                         created_at timestamp(6) not null,
                         id bigint generated by default as identity,
                         updated_at timestamp(6) not null,
                         user_id bigint,
                         image_url TEXT,
                         name varchar(255) not null,
                         primary key (id)
);
create table colors (
                        brightness float4 not null,
                        hue float4 not null,
                        saturation float4 not null,
                        created_at timestamp(6) not null,
                        id bigint generated by default as identity,
                        item_id bigint,
                        updated_at timestamp(6) not null,
                        color_hex varchar(255) not null,
                        primary key (id)
);
create table device_tokens (
                               created_at timestamp(6) not null,
                               id bigint generated by default as identity,
                               updated_at timestamp(6) not null,
                               user_id bigint,
                               device_token TEXT not null,
                               os_type varchar(255) not null check (os_type in ('ANDROID','WEB')),
                               primary key (id),
                               constraint uk_device_token unique (device_token)
);
create table item_usages (
                             last_used_date date,
                             use_count integer not null,
                             created_at timestamp(6) not null,
                             id bigint generated by default as identity,
                             item_id bigint,
                             updated_at timestamp(6) not null,
                             user_id bigint,
                             primary key (id),
                             constraint uk_user_item unique (user_id, item_id)
);
create table items (
                       brand_id bigint,
                       category_id bigint,
                       created_at timestamp(6) not null,
                       id bigint generated by default as identity,
                       material_id bigint,
                       pattern_id bigint,
                       price bigint,
                       updated_at timestamp(6) not null,
                       user_id bigint,
                       image_background_color varchar(255) not null check (image_background_color in ('WHITE','GRAY')),
                       image_url TEXT not null,
                       memo varchar(255),
                       size varchar(255),
                       primary key (id)
);
create table materials (
                           created_at timestamp(6) not null,
                           id bigint generated by default as identity,
                           updated_at timestamp(6) not null,
                           name varchar(255) not null,
                           primary key (id)
);
create table ootd_items (
                            posx float4 not null,
                            posy float4 not null,
                            rotation float4 not null,
                            scale float4 not null,
                            z_index integer not null,
                            created_at timestamp(6) not null,
                            id bigint generated by default as identity,
                            item_id bigint,
                            ootd_id bigint,
                            updated_at timestamp(6) not null,
                            primary key (id)
);
create table ootds (
                       favorite boolean not null,
                       change_item_count bigint not null,
                       created_at timestamp(6) not null,
                       id bigint generated by default as identity,
                       style_id bigint,
                       tpo_id bigint,
                       updated_at timestamp(6) not null,
                       user_id bigint,
                       image_background_color varchar(255) not null check (image_background_color in ('WHITE','GRAY')),
                       image_url TEXT not null,
                       memo varchar(255),
                       name varchar(255) not null,
                       status VARCHAR DEFAULT 'NORMAL' not null check (status in ('NORMAL','ABNORMAL')),
                       primary key (id)
);
create table patterns (
                          created_at timestamp(6) not null,
                          id bigint generated by default as identity,
                          updated_at timestamp(6) not null,
                          name varchar(255) not null,
                          primary key (id)
);
create table seasons (
                         item_id bigint not null,
                         season_name varchar(255) check (season_name in ('SPRING','SUMMER','AUTUMN','WINTER'))
);
create table styles (
                        created_at timestamp(6) not null,
                        id bigint generated by default as identity,
                        updated_at timestamp(6) not null,
                        name varchar(255) not null,
                        primary key (id)
);
create table tpos (
                      created_at timestamp(6) not null,
                      id bigint generated by default as identity,
                      updated_at timestamp(6) not null,
                      name varchar(255) not null,
                      primary key (id)
);
create table user_histories (
                                created_at timestamp(6) not null,
                                id bigint generated by default as identity,
                                updated_at timestamp(6) not null,
                                user_id bigint not null,
                                monthly_ootd_image_url TEXT,
                                year_month varchar(255) not null,
                                primary key (id),
                                constraint uk_user_year_month unique (user_id, year_month)
);
create table users (
                       height float4 not null,
                       weight float4 not null,
                       created_at timestamp(6) not null,
                       fitting_count BIGINT DEFAULT 0 not null,
                       id bigint generated by default as identity,
                       inactive_date timestamp(6),
                       updated_at timestamp(6) not null,
                       body_image_url TEXT,
                       email varchar(255),
                       gender varchar(255) check (gender in ('MAN','WOMAN')),
                       nickname varchar(255) unique,
                       role VARCHAR(255) NOT NULL CHECK (role in ('ADMIN','USER')),
                       oauth_id varchar(255) not null,
                       oauth_provider varchar(255) not null check (oauth_provider in ('KAKAO','GOOGLE')),
                       profile_image_url TEXT,
                       rank VARCHAR DEFAULT 'LV1' not null check (rank in ('LV1','LV2','LV3','LV4','LV5')),
                       status VARCHAR DEFAULT 'ACTIVE' not null check (status in ('ACTIVE','DELETED')),
                       primary key (id),
                       constraint uk_oauth_provider_id unique (oauth_provider, oauth_id)
);

-- 제약조건 및 외래키
alter table if exists calendars
    add constraint FK38rctl67lsi19ya43ay3ihguy
    foreign key (ootd_id)
    references ootds;
alter table if exists calendars
    add constraint FK2ef443fpfyuaay9nc09tvhjre
    foreign key (user_id)
    references users;
alter table if exists categories
    add constraint FKsaok720gsu4u2wrgbk10b5n8d
    foreign key (parent_id)
    references categories;
alter table if exists closet_items
    add constraint FK939orge5t5odcfllb3e33uofr
    foreign key (closet_id)
    references closets;
alter table if exists closet_items
    add constraint FK2g9sd6vuam7j4m2dbl8gbqnsb
    foreign key (item_id)
    references items;
alter table if exists closets
    add constraint FKo248kv0ijo2jsxtpxqscph0aa
    foreign key (user_id)
    references users;
alter table if exists colors
    add constraint FKjprpqalka945pkbuh36hjybkx
    foreign key (item_id)
    references items;
alter table if exists device_tokens
    add constraint FKhc7d11bnr8x9gs5biohdhnx1c
    foreign key (user_id)
    references users;
alter table if exists item_usages
    add constraint FKg36cmxckfx4o9x40cayn50yff
    foreign key (item_id)
    references items;
alter table if exists item_usages
    add constraint FKdqes9803729y6xw1kb6aup0ob
    foreign key (user_id)
    references users;
alter table if exists items
    add constraint FKi0gnxi21mo1gmbl3q2cqvpx69
    foreign key (brand_id)
    references brands;
alter table if exists items
    add constraint FKjcdcde7htb3tyjgouo4g9xbmr
    foreign key (category_id)
    references categories;
alter table if exists items
    add constraint FK1ss5q4kb7amogifugfg928he4
    foreign key (material_id)
    references materials;
alter table if exists items
    add constraint FKoy4vj6xiykaqkbwkxxsymhoeq
    foreign key (pattern_id)
    references patterns;
alter table if exists items
    add constraint FKft8pmhndq1kntvyfaqcybhxvx
    foreign key (user_id)
    references users;
alter table if exists ootd_items
    add constraint FKmkrickpgn7h89c3xy79jbp4l1
    foreign key (item_id)
    references items;
alter table if exists ootd_items
    add constraint FKsgldj3ncic5t0as2jy0vxdebu
    foreign key (ootd_id)
    references ootds;
alter table if exists ootds
    add constraint FKjgf4jvp54irelbhlmaw10ft2w
    foreign key (style_id)
    references styles;
alter table if exists ootds
    add constraint FK4039981m2ghv0ftudcip2juyj
    foreign key (tpo_id)
    references tpos;
alter table if exists ootds
    add constraint FKh2xw5ln5osm1q0jyah5vgnpng
    foreign key (user_id)
    references users;
alter table if exists seasons
    add constraint FK7y2jgtmpdcsba3c23ux5iisif
    foreign key (item_id)
    references items;
alter table if exists user_histories
    add constraint FKiujv5qxteue9li4u17iyod9cb
    foreign key (user_id)
    references users;
