/* 1. 기존 colors 테이블 구조 변경 */
-- 기존 colors는 아이템에 종속된 데이터였으나, 이제는 공통 색상(빨강, 파랑 등)을 관리하는 테이블로 변경됩니다.
-- 기존 데이터와 구조가 완전히 다르므로 기존 데이터를 비우고 컬럼을 수정합니다.

TRUNCATE TABLE colors CASCADE; -- 데이터 초기화 (개발 단계라 가정)

-- 불필요한 기존 컬럼 제거
ALTER TABLE colors DROP COLUMN IF EXISTS item_id;
ALTER TABLE colors DROP COLUMN IF EXISTS brightness;
ALTER TABLE colors DROP COLUMN IF EXISTS hue;
ALTER TABLE colors DROP COLUMN IF EXISTS saturation;
ALTER TABLE colors DROP COLUMN IF EXISTS color_hex;

-- 새로운 컬럼 추가
ALTER TABLE colors ADD COLUMN name VARCHAR(255) NOT NULL;

/* 2. items_color 중간 테이블 생성 */
CREATE TABLE items_color (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             item_id BIGINT NOT NULL,
                             color_id BIGINT NOT NULL,
                             created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
                             updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
                             PRIMARY KEY (id)
);

/* 3. 외래키(Foreign Key) 설정 */
ALTER TABLE items_color
    ADD CONSTRAINT fk_items_color_item
        FOREIGN KEY (item_id)
            REFERENCES items (id);

ALTER TABLE items_color
    ADD CONSTRAINT fk_items_color_color
        FOREIGN KEY (color_id)
            REFERENCES colors (id);

/* 4. 기본 색상 데이터 추가 (선택 사항) */INSERT INTO colors (name, created_at, updated_at) VALUES
                                                                                   ('BLACK', NOW(), NOW()),
                                                                                   ('WHITE', NOW(), NOW()),
                                                                                   ('GRAY', NOW(), NOW()),
                                                                                   ('BEIGE', NOW(), NOW()),
                                                                                   ('BROWN', NOW(), NOW()),
                                                                                   ('RED', NOW(), NOW()),
                                                                                   ('ORANGE', NOW(), NOW()),
                                                                                   ('YELLOW', NOW(), NOW()),
                                                                                   ('GREEN', NOW(), NOW()),
                                                                                   ('BLUE', NOW(), NOW()),
                                                                                   ('PURPLE', NOW(), NOW()),
                                                                                   ('PINK', NOW(), NOW());